In [2]:
import numpy as np 
import pandas as pd 
import math 

In [3]:
df = pd.read_csv("input.csv")
df.head()

jarak_pasar  kepadatan_penduduk  jarak_pabrik  jarak_gudang  harga_tanah
0         0.75                2000            18            50          500
1         0.50                1500            20            40          450
2         0.90                2050            35            35          800

In [5]:
matrix = df.values
matrix

array([[7.50e-01, 2.00e+03, 1.80e+01, 5.00e+01, 5.00e+02],
       [5.00e-01, 1.50e+03, 2.00e+01, 4.00e+01, 4.50e+02],
       [9.00e-01, 2.05e+03, 3.50e+01, 3.50e+01, 8.00e+02]])

In [14]:
#NORMALISASI
normalised_matrix = []
for row in matrix.T:
    div = np.sqrt(sum([a**2 for a in row]))
    normalised_matrix.append([a/div for a in row])
normalised_matrix = np.array(normalised_matrix).T
normalised_matrix

array([[0.5888015 , 0.61861423, 0.40772429, 0.68518871, 0.47836487],
       [0.39253434, 0.46396067, 0.45302699, 0.54815097, 0.43052839],
       [0.7065618 , 0.63407959, 0.79279723, 0.4796321 , 0.7653838 ]])

In [16]:
#PEMBOBOTAN
weights = [5, 3, 4, 4, 2]
weighted_matrix = normalised_matrix*weights
weighted_matrix

array([[2.94400752, 1.8558427 , 1.63089716, 2.74075484, 0.95672975],
       [1.96267168, 1.39188202, 1.81210796, 2.19260387, 0.86105677],
       [3.53280902, 1.90223876, 3.17118893, 1.91852839, 1.53076759]])

In [18]:
#MENCARI SOLUSI IDEAL POSITIF & NEGATIF
benefit = [False, True, False, True, False]
positive_ideal = []
negative_ideal = []
for i in range(len(benefit)):
    if benefit[i]:
        positive_ideal.append(max(weighted_matrix.T[i]))
        negative_ideal.append(min(weighted_matrix.T[i]))
    else :
        positive_ideal.append(min(weighted_matrix.T[i]))
        negative_ideal.append(max(weighted_matrix.T[i]))
positive_ideal = np.array(positive_ideal)
negative_ideal = np.array(negative_ideal)
print("Positive Ideal:")
print(positive_ideal)
print("Negative Ideal:")
print(negative_ideal)

Positive Ideal:
[1.96267168 1.90223876 1.63089716 2.74075484 0.86105677]
Negative Ideal:
[3.53280902 1.39188202 3.17118893 1.91852839 1.53076759]


In [41]:
#MENGHITUNG JARAK DENGAN IDEAL
positive_distance = np.sqrt(((weighted_matrix-positive_ideal)**2).sum(axis=1))
negative_distance = np.sqrt(((weighted_matrix-negative_ideal)**2).sum(axis=1))
print("Positive Distance:")
print(positive_distance)
print("Negative Distance:")
print(negative_distance)

Positive Distance:
[0.9870795  0.77056527 2.44180239]
Negative Distance:
[1.98494867 2.19910489 0.51035674]


In [42]:
#MENGHITUNG NILAI PREFERENSI
v = [a/(a+b) for a,b in zip(negative_distance, positive_distance)]
v

[0.6678768016498927, 0.7405215963672054, 0.1728757559008171]

In [43]:
np.argmax(v)

1